spool RPRO_EXECUTE_OUTPUT.txt

SELECT NAME,TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI') TIME_STAMP FROM V$DATABASE;

SET DEFINE OFF;

SET SERVEROUTPUT ON;


PROMPT RPRO_SIEMENS_REP_CUSTOM_PKG.pks
@RPRO_SIEMENS_REP_CUSTOM_PKG.pks

PROMPT RPRO_SIEMENS_REP_CUSTOM_PKG.pkb
@RPRO_SIEMENS_REP_CUSTOM_PKG.pkb

PROMPT REP_DEL_SCRIPT.sql
@REP_DEL_SCRIPT.sql

PROMPT REP_CREATE_SCRIPT.sql
@REP_CREATE_SCRIPT.sql

spool off;
EXIT;


