spool RPRO_EXECUTE_OUTPUT.txt

SELECT NAME,TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI') TIME_STAMP FROM V$DATABASE;

SET DEFINE OFF;

SET SERVEROUTPUT ON;


PROMPT RPRO_RC_LINE_CBILL_V
@RPRO_RC_LINE_CBILL_V.sql;

PROMPT RPRO_CUST_RI_LN_ACCT_SUMM_V
@RPRO_CUST_RI_LN_ACCT_SUMM_V.sql;

PROMPT RPRO_CUST_ACCT_SUMM_V
@RPRO_CUST_ACCT_SUMM_V.sql;

PROMPT RPRO_RI_CUST_INSIGHT_V
@RPRO_RI_CUST_INSIGHT_V.sql;

PROMPT Rep_Script
@Rep_Script.sql;

PROMPT RPRO_CUST_BILL_IDX_1
@RPRO_CUST_BILL_IDX_1.sql;


spool off;
EXIT;


