  CREATE OR REPLACE VIEW RPRO_CUST_RI_LN_ACCT_SUMM_V 
  ("PRD_ID", "PERIOD_NAME", "PRD_START_DT", "PRD_END_DT",
  "RC_ID", "RC_VER", "LINE_ID", "ROOT_LINE_ID", "ACCT_SEGS", 
  "ACCT_TYPE_ID", "ACCT_TYPE", "ACCT_GROUP", "DEF_REC_FLAG",
  "VC_FLAG", "COST_FLAG", "INCL_MANUAL_JE_FLAG", "INCL_NETTING_FLAG",
  "VC_CLR_FLAG", "MANUAL_JE", "NETTING_ENTRY", "SCHD_TYPE",
  "CLIENT_ID", "BOOK_ID", "SEC_ATR_VAL", "QT_NM", "PD_YR",
  "PD_NM", "CRTD_BY", "CRTD_DT", "UPDT_BY", "UPDT_DT", "F_TL_AT",
  "F_TL_AT_PS", "F_TL_AT_UN", "F_RT_AR", "F_AT", "F_AT_PS",
  "F_AT_UN", "F_AR_AT", "F_AR_PS", "F_AR_UN", "F_TL_BB", 
  "F_TL_AD", "F_TL_RL", "F_TL_EB", "F_TL_RL_PS", "F_TL_RL_UN",
  "F_TL_NT", "F_NT", "F_AL_NT", "F_BB", "F_AD", "F_RL", "F_EB",
  "F_RL_PS", "F_RL_UN", "F_AL_BB", "F_AL_AD", "F_AL_RL", "F_AL_EB",
  "F_AL_PS", "F_AL_UN", "F_TL_AT_QT", "F_AT_QT", "F_AR_AT_QT",
  "F_RT_AR_QT", "F_TL_BB_QT", "F_TL_AD_QT", "F_TL_RL_QT",
  "F_BB_QT", "F_AD_QT", "F_RL_QT", "F_AL_BB_QT", "F_AL_AD_QT",
  "F_AL_RL_QT", "F_TL_AT_YT", "F_AT_YT", "F_AR_AT_YT", "F_RT_AR_YT",
  "F_TL_BB_YT", "F_TL_AD_YT", "F_TL_RL_YT", "F_BB_YT", "F_AD_YT",
  "F_RL_YT", "F_AL_BB_YT", "F_AL_AD_YT", "F_AL_RL_YT", "F_TL_AT_UT",
  "F_RV_AT_UT", "F_AR_AT_UT", "F_TL_BB_UT", "F_TL_AD_UT", "F_TL_RL_UT",
  "F_BB_UT", "F_AD_UT", "F_RL_UT", "F_AL_BB_UT", "F_AL_AD_UT", "F_AL_RL_UT",
  "T_TL_AT", "T_TL_AT_PS", "T_TL_AT_UN", "T_AT", "T_AT_PS", "T_AT_UN",
  "T_AR_AT", "T_AR_PS", "T_AR_UN", "T_RT_AR", "T_TL_BB", "T_TL_AD", "T_TL_RL",
  "T_TL_EB", "T_TL_RL_PS", "T_TL_RL_UN", "T_TL_NT", "T_NT", "T_AL_NT", "T_BB",
  "T_AD", "T_RL", "T_EB", "T_RL_PS", "T_RL_UN", "T_AL_BB", "T_AL_AD", "T_AL_RL",
  "T_AL_EB", "T_AL_PS", "T_AL_UN", "T_TL_AT_QT", "T_AT_QT", "T_AR_AT_QT",
  "T_RT_AR_QT", "T_TL_BB_QT", "T_TL_AD_QT", "T_TL_RL_QT", "T_BB_QT", "T_AD_QT", 
  "T_RL_QT", "T_AL_BB_QT", "T_AL_AD_QT", "T_AL_RL_QT", "T_TL_AT_YT", "T_AT_YT",
  "T_AR_AT_YT", "T_RT_AR_YT", "T_TL_BB_YT", "T_TL_AD_YT", "T_TL_RL_YT",
  "T_BB_YT", "T_AD_YT", "T_RL_YT", "T_AL_BB_YT", "T_AL_AD_YT", "T_AL_RL_YT",
  "T_TL_AT_UT", "T_RV_AT_UT", "T_AR_AT_UT", "T_TL_BB_UT", "T_TL_AD_UT",
  "T_TL_RL_UT", "T_BB_UT", "T_AD_UT", "T_RL_UT", "T_AL_BB_UT", "T_AL_AD_UT",
  "T_AL_RL_UT", "R_TL_AT", "R_TL_AT_PS", "R_TL_AT_UN", "R_RT_AR", "R_AT",
  "R_AT_PS", "R_AT_UN", "R_AR_AT", "R_AR_PS", "R_AR_UN", "R_TL_BB", "R_TL_AD",
  "R_TL_RL", "R_TL_EB", "R_TL_RL_PS", "R_TL_RL_UN", "R_TL_NT", "R_NT", "R_AL_NT",
  "R_BB", "R_AD", "R_RL", "R_EB", "R_RL_PS", "R_RL_UN", "R_AL_BB", "R_AL_AD",
  "R_AL_RL", "R_AL_EB", "R_AL_PS", "R_AL_UN", "R_TL_AT_QT", "R_AT_QT", "R_AR_AT_QT",
  "R_RT_AR_QT", "R_TL_BB_QT", "R_TL_AD_QT", "R_TL_RL_QT", "R_BB_QT", "R_AD_QT",
  "R_RL_QT", "R_AL_BB_QT", "R_AL_AD_QT", "R_AL_RL_QT", "R_TL_AT_YT", "R_AT_YT",
  "R_AR_AT_YT", "R_RT_AR_YT", "R_TL_BB_YT", "R_TL_AD_YT", "R_TL_RL_YT", "R_BB_YT",
  "R_AD_YT", "R_RL_YT", "R_AL_BB_YT", "R_AL_AD_YT", "R_AL_RL_YT", "R_TL_AT_UT",
  "R_RV_AT_UT", "R_AR_AT_UT", "R_TL_BB_UT", "R_TL_AD_UT", "R_TL_RL_UT", "R_BB_UT",
  "R_AD_UT", "R_RL_UT", "R_AL_BB_UT", "R_AL_AD_UT", "R_AL_RL_UT", "F_UNBL_AT",
  "F_UNBL_PS", "F_UNBL_UN", "F_UNBL_AT_QT", "F_UNBL_AT_YT", "F_UNBL_AT_UT","F_UNBL_UTD",
  "T_UNBL_AT", "T_UNBL_PS", "T_UNBL_UN", "T_UNBL_AT_QT", "T_UNBL_AT_YT",
  "T_UNBL_AT_UT","T_UNBL_UTD", "R_UNBL_AT", "R_UNBL_PS", "R_UNBL_UN", "R_UNBL_AT_QT",
  "R_UNBL_AT_YT", "R_UNBL_AT_UT","R_UNBL_UTD","T_CONTRA_RL_UT","F_CONTRA_RL_UT","R_CONTRA_RL_UT",
  "F_RT", "F_AR_RT", "T_RT", "T_AR_RT", "R_RT", "R_AR_RT", "T_TL_NT_RL", "F_TL_NT_RL",
  "R_TL_NT_RL", "T_NT_RL", "F_NT_RL", "R_NT_RL", "T_AL_NT_RL", "F_AL_NT_RL", "R_AL_NT_RL",
  "T_TL_CA_IM", "F_TL_CA_IM", "R_TL_CA_IM", "T_TL_CA_IM_QT", "F_TL_CA_IM_QT", "R_TL_CA_IM_QT",
  "T_TL_CA_IM_YT", "F_TL_CA_IM_YT", "R_TL_CA_IM_YT", "T_CA_IM", "F_CA_IM", "R_CA_IM",
  "T_AL_CA_IM", "F_AL_CA_IM", "R_AL_CA_IM", "T_CA_IM_QT", "F_CA_IM_QT", "R_CA_IM_QT",
  "T_AL_CA_IM_QT", "F_AL_CA_IM_QT", "R_AL_CA_IM_QT", "T_CA_IM_YT", "F_CA_IM_YT",
  "R_CA_IM_YT", "T_AL_CA_IM_YT", "F_AL_CA_IM_YT", "R_AL_CA_IM_YT", "T_TL_CA_IM_UT",
  "F_TL_CA_IM_UT", "R_TL_CA_IM_UT", "T_CA_IM_UT", "F_CA_IM_UT", "R_CA_IM_UT", 
  "T_AL_CA_IM_UT", "F_AL_CA_IM_UT", "R_AL_CA_IM_UT", "F_RT_QT", "F_AR_RT_QT",
  "T_RT_QT", "T_AR_RT_QT", "R_RT_QT", "R_AR_RT_QT", "F_RT_YT", "F_AR_RT_YT", 
  "T_RT_YT", "T_AR_RT_YT", "R_RT_YT", "R_AR_RT_YT", "T_VC_BB", "T_VC_AD",
  "T_VC_RL", "T_VC_CLM", "T_VC_EB", "F_VC_BB", "F_VC_AD", "F_VC_RL", "F_VC_CLM",
  "F_VC_EB", "R_VC_BB", "R_VC_AD", "R_VC_RL", "R_VC_CLM", "R_VC_EB", "T_VC_BB_QT",
  "T_VC_AD_QT", "T_VC_RL_QT", "T_VC_CLM_QT", "F_VC_BB_QT", "F_VC_AD_QT", "F_VC_RL_QT",
  "F_VC_CLM_QT", "R_VC_BB_QT", "R_VC_AD_QT", "R_VC_RL_QT", "R_VC_CLM_QT", "T_VC_BB_YT",
  "T_VC_AD_YT", "T_VC_RL_YT", "T_VC_CLM_YT", "F_VC_BB_YT", "F_VC_AD_YT", "F_VC_RL_YT",
  "F_VC_CLM_YT", "R_VC_BB_YT", "R_VC_AD_YT", "R_VC_RL_YT", "R_VC_CLM_YT", "T_VC_UN", "F_VC_UN",
  "R_VC_UN", "T_VC_PS", "F_VC_PS", "R_VC_PS", "T_TL_VC_UT", "F_TL_VC_UT", "R_TL_VC_UT",
  "PAYABLES_ACCT_FLAG", "LT_T_BAL", "LT_F_BAL", "LT_R_BAL","T_CUM_BILL_UTD","F_CUM_BILL_UTD") AS 
  WITH RPRO_RI_ACCT_GRP_VM AS (SELECT /*+ MATERIALIZE RESULT_CACHE */
                                  id,name,def_rec_flag,vc_flag,vc_clr_flag
                                  ,client_id,incl_netting_flag,incl_manual_je_flag
                                  ,cost_flag,acct_group,payables_acct_flag FROM RPRO_RI_ACCT_GRP_V),
     RPRO_CALENDAR_V AS (SELECT /*+ MATERIALIZE RESULT_CACHE */ ID,period_num
                        ,period_name,period_year,qtr_num,start_date,end_date
                        , qtr_start_dt,qtr_end_dt,year_start_dt,year_end_dt,client_id from rpro_calendar_g)
SELECT
/**************************************************************************************************
* Name        : RPRO_RI_LN_ACCT_SUMM_V                                                            *
* Author      : LEEYO                                                                             *
* Date        : 18-APR-16                                                                         *
* Description :                                                                                   *
* #Version: 14
* #Tag: 36.011.00
* #Last Modified by: njayapaul | 2019-10-22 23:22:51 | b3339eca
/**************************************************************************************************
* Copyright - 2009 Leeyo Software. All rights reserved                                            *
*                                                                                                 *
* Leeyo REVPRO product is an application modified and extended for clients, based on the REVPRO   *
* owned by Leeyo Software.                                                                        *
* All related documentation, code, methods and other materials concerning REVPRO are the property *
* of Leeyo Software and may not be reused, copied, or transmitted in material or electronic form  *
* without the express written consent of Leeyo Software.                                          *
**************************************************************************************************/
 CAL.ID AS PRD_ID
,CAL.PERIOD_NAME AS PERIOD_NAME
,CAL.START_DATE AS PRD_START_DT
,CAL.END_DATE AS PRD_END_DT
,SUMM.RC_ID AS RC_ID
,SUMM.RC_VER AS RC_VER
,SUMM.LINE_ID AS LINE_ID
,SUMM.ROOT_LINE_ID AS ROOT_LINE_ID
,SUMM.ACCTG_SEGS AS ACCT_SEGS
,SUMM.ACCT_TYPE_ID AS ACCT_TYPE_ID
,ACG.NAME AS ACCT_TYPE
,NVL(ACG.ACCT_GROUP,'UNKNOWN') as ACCT_GROUP
,ACG.DEF_REC_FLAG AS DEF_REC_FLAG
,ACG.VC_FLAG AS VC_FLAG
,ACG.COST_FLAG AS COST_FLAG
,ACG.INCL_MANUAL_JE_FLAG
,ACG.INCL_NETTING_FLAG
,ACG.VC_CLR_FLAG
,DECODE(SUMM.SCHD_TYPE,'M','Y') AS MANUAL_JE
,SUMM.NETTING_ENTRY_FLAG AS NETTING_ENTRY
,SUMM.SCHD_TYPE AS SCHD_TYPE
,SUMM.CLIENT_ID as CLIENT_ID
,SUMM.BOOK_ID as BOOK_ID
,SUMM.SEC_ATR_VAL as SEC_ATR_VAL
,CAL.QTR_NUM AS QT_NM
,CAL.PERIOD_YEAR AS PD_YR
,CAL.PERIOD_NUM AS PD_NM
,SUMM.CRTD_BY AS CRTD_BY
,SUMM.CRTD_DT AS CRTD_DT
,SUMM.UPDT_BY AS UPDT_BY
,SUMM.UPDT_DT AS UPDT_DT
-- **** Func ****
-- **** PTD ****
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_AT,0) ELSE 0 END AS F_TL_AT         -- Total Activity
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_TL_AT_PS                    -- Tot Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_TL_AT_UN                    -- Tot Activity Unposted
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC', 'EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_RT_AR,0) ELSE 0 END AS F_RT_AR  -- Tot Retro Adj
--
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_AT,0) ELSE 0 END AS F_AT                            -- Activity
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_AT_PS                    -- Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_AT_UN      -- Activity Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_AT,0) ELSE 0 END AS F_AR_AT                    -- Alloc Activity
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_AR_PS                    -- Alloc Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_AR_UN      -- Alloc Activity Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.F_BB,SUMM.F_EB) ELSE 0 END AS F_TL_BB -- Tot Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.F_AD,0) ELSE 0 END AS F_TL_AD             -- Tot Add
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_RL,0) ELSE 0 END AS F_TL_RL                      -- Tot Release
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.F_EB,0) ELSE 0 END AS F_TL_EB                                                  -- Tot End Bal
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_TL_RL_PS                    -- Tot Posted
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_TL_RL_UN                    -- Tot Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_NT,0) ELSE 0 END AS F_TL_NT -- Netting Entry
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_NT,0) ELSE 0 END AS F_NT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_NT,0) ELSE 0 END AS F_AL_NT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.F_BB,SUMM.F_EB) ELSE 0 END AS F_BB    -- Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.F_AD,0) ELSE 0 END AS F_AD                -- Adds
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_RL,0) ELSE 0 END AS F_RL                        -- Releases
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.F_EB,0) ELSE 0 END AS F_EB                                                    -- End Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_RL_PS                    -- Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_RL_UN                    -- Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.F_BB,SUMM.F_EB) ELSE 0 END AS F_AL_BB -- Alloc Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.F_AD,0) ELSE 0 END AS F_AL_AD             -- Alloc Add
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_RL,0) ELSE 0 END AS F_AL_RL                     -- Alloc Release
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.F_EB,0) ELSE 0 END AS F_AL_EB                                                 -- Alloc End Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_AL_PS                    -- Alloc Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_AL_UN                    -- Alloc Unposted
-- **** QTD **** --
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_AT_QT,0) ELSE 0 END AS F_TL_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_AT_QT,0) ELSE 0 END AS F_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_AT_QT,0) ELSE 0 END AS F_AR_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_RT_AR_QT,0) ELSE 0 END AS F_RT_AR_QT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.F_BB_QT,SUMM.F_EB) ELSE 0 END AS F_TL_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.F_AD_QT,0) ELSE 0 END AS F_TL_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_RL_QT,0) ELSE 0 END AS F_TL_RL_QT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.F_BB_QT,SUMM.F_EB) ELSE 0 END AS F_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.F_AD_QT,0) ELSE 0 END AS F_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_RL_QT,0) ELSE 0 END AS F_RL_QT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.F_BB_QT,SUMM.F_EB) ELSE 0 END AS F_AL_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.F_AD_QT,0) ELSE 0 END AS F_AL_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_RL_QT,0) ELSE 0 END AS F_AL_RL_QT
-- **** YTD **** --
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_AT_YT,0) ELSE 0 END AS F_TL_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_AT_YT,0) ELSE 0 END AS F_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_AT_YT,0) ELSE 0 END AS F_AR_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_RT_AR_YT,0) ELSE 0 END AS F_RT_AR_YT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.F_BB_YT,SUMM.F_EB) ELSE 0 END AS F_TL_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.F_AD_YT,0) ELSE 0 END AS F_TL_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_RL_YT,0) ELSE 0 END AS F_TL_RL_YT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.F_BB_YT,SUMM.F_EB) ELSE 0 END AS F_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.F_AD_YT,0) ELSE 0 END AS F_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_RL_YT,0) ELSE 0 END AS F_RL_YT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.F_BB_YT,SUMM.F_EB) ELSE 0 END AS F_AL_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.F_AD_YT,0) ELSE 0 END AS F_AL_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_RL_YT,0) ELSE 0 END AS F_AL_RL_YT
--UTD
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') 
      AND  ACG.ID != 'S'
 THEN NVL(F_AT_UT,0) ELSE 0 END AS F_TL_AT_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN NVL(F_AT_UT,0) ELSE 0 END AS F_RV_AT_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN NVL(F_AT_UT,0) ELSE 0 END AS F_AR_AT_UT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.F_BB_UT,0) ELSE 0 END AS F_TL_BB_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.F_AD_UT,0) ELSE 0 END AS F_TL_AD_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.F_RL_UT,0) ELSE 0 END AS F_TL_RL_UT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.F_BB_UT,0) ELSE 0 END AS F_BB_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.F_AD_UT,0) ELSE 0 END AS F_AD_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.F_RL_UT,0) ELSE 0 END AS F_RL_UT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.F_BB_UT,0) ELSE 0 END AS F_AL_BB_UT --AL Beg Bal UTD
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.F_AD_UT,0) ELSE 0 END AS F_AL_AD_UT --AL Add UTD
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.F_RL_UT,0) ELSE 0 END AS F_AL_RL_UT --AL Release UTD
-- **** Trans ****
-- **** PTD ****
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_AT,0) ELSE 0 END AS T_TL_AT         -- Total Activity
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END as T_TL_AT_PS                    -- Tot Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END as T_TL_AT_UN      -- Tot Activity Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_AT,0) ELSE 0 END AS T_AT                            -- Activity
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END as T_AT_PS                    -- Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END as T_AT_UN      -- Activity Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_AT,0) ELSE 0 END AS T_AR_AT                    -- Alloc Activity
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END AS T_AR_PS                    -- Alloc Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END AS T_AR_UN      -- Alloc Activity Unposted
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC', 'EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_RT_AR,0) ELSE 0 END AS T_RT_AR  -- Tot Retro Adj
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.T_BB,SUMM.T_EB) ELSE 0 END AS T_TL_BB -- Tot Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.T_AD,0) ELSE 0 END AS T_TL_AD             -- Tot Add
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_RL,0) ELSE 0 END AS T_TL_RL                      -- Tot Release
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.T_EB,0) ELSE 0 END AS T_TL_EB                                                  -- Tot End Bal
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END as T_TL_RL_PS                    -- Tot Posted
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END as T_TL_RL_UN                    -- Tot Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_NT,0) ELSE 0 END AS T_TL_NT -- Netting Entry
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_NT,0) ELSE 0 END AS T_NT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_NT,0) ELSE 0 END AS T_AL_NT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.T_BB,SUMM.T_EB) ELSE 0 END AS T_BB    -- Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.T_AD,0) ELSE 0 END AS T_AD                -- Adds
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_RL,0) ELSE 0 END AS T_RL                        -- Releases
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.T_EB,0) ELSE 0 END AS T_EB                                                    -- End Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END as T_RL_PS                    -- Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END as T_RL_UN                    -- Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.T_BB,SUMM.T_EB) ELSE 0 END AS T_AL_BB -- Alloc Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.T_AD,0) ELSE 0 END AS T_AL_AD             -- Alloc Add
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_RL,0) ELSE 0 END AS T_AL_RL                     -- Alloc Release
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.T_EB,0) ELSE 0 END AS T_AL_EB                                                 -- Alloc End Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END as T_AL_PS                    -- Alloc Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END as T_AL_UN                    -- Alloc Unposted
-- **** QTD **** --
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_AT_QT,0) ELSE 0 END AS T_TL_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_AT_QT,0) ELSE 0 END AS T_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_AT_QT,0) ELSE 0 END AS T_AR_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_RT_AR_QT,0) ELSE 0 END AS T_RT_AR_QT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.T_BB_QT,SUMM.T_EB) ELSE 0 END AS T_TL_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.T_AD_QT,0) ELSE 0 END AS T_TL_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_RL_QT,0) ELSE 0 END AS T_TL_RL_QT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.T_BB_QT,SUMM.T_EB) ELSE 0 END AS T_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.T_AD_QT,0) ELSE 0 END AS T_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_RL_QT,0) ELSE 0 END AS T_RL_QT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.T_BB_QT,SUMM.T_EB) ELSE 0 END AS T_AL_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.T_AD_QT,0) ELSE 0 END AS T_AL_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_RL_QT,0) ELSE 0 END AS T_AL_RL_QT
-- **** YTD **** --
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_AT_YT,0) ELSE 0 END AS T_TL_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_AT_YT,0) ELSE 0 END AS T_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_AT_YT,0) ELSE 0 END AS T_AR_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_RT_AR_YT,0) ELSE 0 END AS T_RT_AR_YT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.T_BB_YT,SUMM.T_EB) ELSE 0 END AS T_TL_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.T_AD_YT,0) ELSE 0 END AS T_TL_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_RL_YT,0) ELSE 0 END AS T_TL_RL_YT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.T_BB_YT,SUMM.T_EB) ELSE 0 END AS T_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.T_AD_YT,0) ELSE 0 END AS T_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_RL_YT,0) ELSE 0 END AS T_RL_YT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.T_BB_YT,SUMM.T_EB) ELSE 0 END AS T_AL_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.T_AD_YT,0) ELSE 0 END AS T_AL_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_RL_YT,0) ELSE 0 END AS T_AL_RL_YT
--UTD
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') 
      AND  ACG.ID != 'S'
      THEN NVL(T_AT_UT,0) ELSE 0 END AS T_TL_AT_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN NVL(T_AT_UT,0) ELSE 0 END AS T_RV_AT_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN NVL(T_AT_UT,0) ELSE 0 END AS T_AR_AT_UT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.T_BB_UT,0) ELSE 0 END AS T_TL_BB_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.T_AD_UT,0) ELSE 0 END AS T_TL_AD_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.T_RL_UT,0) ELSE 0 END AS T_TL_RL_UT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.T_BB_UT,0) ELSE 0 END AS T_BB_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.T_AD_UT,0) ELSE 0 END AS T_AD_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.T_RL_UT,0) ELSE 0 END AS T_RL_UT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.T_BB_UT,0) ELSE 0 END AS T_AL_BB_UT --AL Beg Bal UTD
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.T_AD_UT,0) ELSE 0 END AS T_AL_AD_UT --AL Add UTD
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.T_RL_UT,0) ELSE 0 END AS T_AL_RL_UT --AL Release UTD
-- **** Report ****
-- **** PTD ****
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_AT,0) ELSE 0 END AS R_TL_AT         -- Total Activity
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END as R_TL_AT_PS                    -- Tot Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END as R_TL_AT_UN                    -- Tot Activity Unposted
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC', 'EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_RT_AR,0) ELSE 0 END AS R_RT_AR  -- Tot Retro Adj
--
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_AT,0) ELSE 0 END AS R_AT                            -- Activity
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END as R_AT_PS                    -- Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END as R_AT_UN                    -- Activity Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_AT,0) ELSE 0 END AS R_AR_AT                    -- Alloc Activity
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END AS R_AR_PS                    -- Alloc Activity Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END AS R_AR_UN                    -- Alloc Activity Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.R_BB,SUMM.R_EB) ELSE 0 END AS R_TL_BB -- Tot Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.R_AD,0) ELSE 0 END AS R_TL_AD             -- Tot Add
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_RL,0) ELSE 0 END AS R_TL_RL                      -- Tot Release
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.R_EB,0) ELSE 0 END AS R_TL_EB                                                  -- Tot End Bal
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END as R_TL_RL_PS                    -- Tot Posted
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END as R_TL_RL_UN                    -- Tot Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_NT,0) ELSE 0 END AS R_TL_NT -- Netting Entry
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_NT,0) ELSE 0 END AS R_NT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_NT,0) ELSE 0 END AS R_AL_NT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.R_BB,SUMM.R_EB) ELSE 0 END AS R_BB    -- Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.R_AD,0) ELSE 0 END AS R_AD                -- Adds
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_RL,0) ELSE 0 END AS R_RL                        -- Releases
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.R_EB,0) ELSE 0 END AS R_EB                                                    -- End Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END as R_RL_PS                    -- Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END as R_RL_UN                    -- Unposted
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.R_BB,SUMM.R_EB) ELSE 0 END AS R_AL_BB -- Alloc Beg Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,SUMM.R_AD,0) ELSE 0 END AS R_AL_AD             -- Alloc Add
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_RL,0) ELSE 0 END AS R_AL_RL                     -- Alloc Release
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.R_EB,0) ELSE 0 END AS R_AL_EB                                                 -- Alloc End Bal
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END as R_AL_PS                    -- Alloc Posted
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END as R_AL_UN                    -- Alloc Unposted
-- **** QTD **** --
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_AT_QT,0) ELSE 0 END AS R_TL_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_AT_QT,0) ELSE 0 END AS R_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_AT_QT,0) ELSE 0 END AS R_AR_AT_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_RT_AR_QT,0) ELSE 0 END AS R_RT_AR_QT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.R_BB_QT,SUMM.R_EB) ELSE 0 END AS R_TL_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.R_AD_QT,0) ELSE 0 END AS R_TL_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_RL_QT,0) ELSE 0 END AS R_TL_RL_QT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.R_BB_QT,SUMM.R_EB) ELSE 0 END AS R_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.R_AD_QT,0) ELSE 0 END AS R_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_RL_QT,0) ELSE 0 END AS R_RL_QT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.R_BB_QT,SUMM.R_EB) ELSE 0 END AS R_AL_BB_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,SUMM.R_AD_QT,0) ELSE 0 END AS R_AL_AD_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_RL_QT,0) ELSE 0 END AS R_AL_RL_QT
-- **** YTD **** --
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_AT_YT,0) ELSE 0 END AS R_TL_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_AT_YT,0) ELSE 0 END AS R_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_AT_YT,0) ELSE 0 END AS R_AR_AT_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_RT_AR_YT,0) ELSE 0 END AS R_RT_AR_YT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.R_BB_YT,SUMM.R_EB) ELSE 0 END AS R_TL_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.R_AD_YT,0) ELSE 0 END AS R_TL_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_RL_YT,0) ELSE 0 END AS R_TL_RL_YT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.R_BB_YT,SUMM.R_EB) ELSE 0 END AS R_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.R_AD_YT,0) ELSE 0 END AS R_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_RL_YT,0) ELSE 0 END AS R_RL_YT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.R_BB_YT,SUMM.R_EB) ELSE 0 END AS R_AL_BB_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,SUMM.R_AD_YT,0) ELSE 0 END AS R_AL_AD_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_RL_YT,0) ELSE 0 END AS R_AL_RL_YT
--UTD
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC','EREC') 
      AND  ACG.ID != 'S'
      THEN NVL(R_AT_UT,0) ELSE 0 END AS R_TL_AT_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'REC' THEN NVL(R_AT_UT,0) ELSE 0 END AS R_RV_AT_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'EREC' THEN NVL(R_AT_UT,0) ELSE 0 END AS R_AR_AT_UT
--
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.R_BB_UT,0) ELSE 0 END AS R_TL_BB_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.R_AD_UT,0) ELSE 0 END AS R_TL_AD_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN NVL(SUMM.R_RL_UT,0) ELSE 0 END AS R_TL_RL_UT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.R_BB_UT,0) ELSE 0 END AS R_BB_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.R_AD_UT,0) ELSE 0 END AS R_AD_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN NVL(SUMM.R_RL_UT,0) ELSE 0 END AS R_RL_UT
--
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.R_BB_UT,0) ELSE 0 END AS R_AL_BB_UT --AL Beg Bal UTD
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.R_AD_UT,0) ELSE 0 END AS R_AL_AD_UT --AL Add UTD
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN NVL(SUMM.R_RL_UT,0) ELSE 0 END AS R_AL_RL_UT --AL Release UTD
-- Unbill
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_AT,0) ELSE 0 END AS F_UNBL_AT -- Unbill Activity
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_PS,0) ELSE 0 END as F_UNBL_PS -- Unbill Activity Posted
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_UN,0) ELSE 0 END as F_UNBL_UN -- Unbill Activity Unposted
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_AT_QT,0) ELSE 0 END AS F_UNBL_AT_QT -- Unbill Activity QTD
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_AT_YT,0) ELSE 0 END AS F_UNBL_AT_YT -- Unbill Activity YTD
,CASE WHEN ACG.ID = 'U' THEN NVL(F_AT_UT,0) ELSE 0 END AS F_UNBL_AT_UT
,CASE WHEN ACG.ID IN ('U','Z') THEN NVL(F_EB,0) ELSE 0 END AS F_UNBL_UTD
-- T
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_AT,0) ELSE 0 END AS T_UNBL_AT -- Unbill Activity
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_PS,0) ELSE 0 END as T_UNBL_PS -- Unbill Activity Posted
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_UN,0) ELSE 0 END as T_UNBL_UN -- Unbill Activity Unposted
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_AT_QT,0) ELSE 0 END AS T_UNBL_AT_QT -- Unbill Activity QTD
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_AT_YT,0) ELSE 0 END AS T_UNBL_AT_YT -- Unbill Activity YTD
,CASE WHEN ACG.ID = 'U' THEN NVL(T_AT_UT,0) ELSE 0 END AS T_UNBL_AT_UT
,CASE WHEN ACG.ID IN ('U','Z') THEN NVL(T_EB,0) ELSE 0 END AS T_UNBL_UTD
-- R
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_AT,0) ELSE 0 END AS R_UNBL_AT -- Unbill Activity
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_PS,0) ELSE 0 END as R_UNBL_PS -- Unbill Activity Posted
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_UN,0) ELSE 0 END as R_UNBL_UN -- Unbill Activity Unposted
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_AT_QT,0) ELSE 0 END AS R_UNBL_AT_QT -- Unbill Activity QTD
,CASE WHEN ACG.ID = 'U' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_AT_YT,0) ELSE 0 END AS R_UNBL_AT_YT -- Unbill Activity YTD
,CASE WHEN ACG.ID = 'U' THEN NVL(R_AT_UT,0) ELSE 0 END AS R_UNBL_AT_UT
,CASE WHEN ACG.ID IN ('U','Z') THEN NVL(R_EB,0) ELSE 0 END AS R_UNBL_UTD
--Custom columns
---------------------------------
,CASE WHEN ACG.ID = 'T' THEN NVL(T_RL_UT,0) ELSE 0 END AS T_CONTRA_RL_UT
,CASE WHEN ACG.ID = 'T' THEN NVL(F_RL_UT,0) ELSE 0 END AS F_CONTRA_RL_UT
,CASE WHEN ACG.ID = 'T' THEN NVL(R_RL_UT,0) ELSE 0 END AS R_CONTRA_RL_UT
---------------------------------
-- Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_RT_AR,0) ELSE 0 END AS F_RT  -- Contractual Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_RT_AR,0) ELSE 0 END AS F_AR_RT  -- Rev Adj Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_RT_AR,0) ELSE 0 END AS T_RT  -- Contractual Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_RT_AR,0) ELSE 0 END AS T_AR_RT  -- Rev Adj Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_RT_AR,0) ELSE 0 END AS R_RT  -- Contractual Retro Adj
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_RT_AR,0) ELSE 0 END AS R_AR_RT  -- Rev Adj Retro
--Netting RL
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,T_NT_RL,0) ELSE 0 END AS T_TL_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,F_NT_RL,0) ELSE 0 END AS F_TL_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,R_NT_RL,0) ELSE 0 END AS R_TL_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_NT_RL,0) ELSE 0 END AS T_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_NT_RL,0) ELSE 0 END AS F_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_NT_RL,0) ELSE 0 END AS R_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,T_NT_RL,0) ELSE 0 END AS T_AL_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,F_NT_RL,0) ELSE 0 END AS F_AL_NT_RL
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,R_NT_RL,0) ELSE 0 END AS R_AL_NT_RL
--Impairment
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * T_CA_IM),0) ELSE 0 END AS T_TL_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * F_CA_IM),0) ELSE 0 END AS F_TL_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * R_CA_IM),0) ELSE 0 END AS R_TL_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * T_CA_IM_QT),0) ELSE 0 END AS T_TL_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * F_CA_IM_QT),0) ELSE 0 END AS F_TL_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * R_CA_IM_QT),0) ELSE 0 END AS R_TL_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * T_CA_IM_YT),0) ELSE 0 END AS T_TL_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * F_CA_IM_YT),0) ELSE 0 END AS F_TL_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * R_CA_IM_YT),0) ELSE 0 END AS R_TL_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * T_CA_IM),0) ELSE 0 END AS T_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * F_CA_IM),0) ELSE 0 END AS F_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * R_CA_IM),0) ELSE 0 END AS R_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * T_CA_IM),0) ELSE 0 END AS T_AL_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * F_CA_IM),0) ELSE 0 END AS F_AL_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.ID,SUMM.PRD_ID,(-1 * R_CA_IM),0) ELSE 0 END AS R_AL_CA_IM
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * T_CA_IM_QT),0) ELSE 0 END AS T_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * F_CA_IM_QT),0) ELSE 0 END AS F_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * R_CA_IM_QT),0) ELSE 0 END AS R_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * T_CA_IM_QT),0) ELSE 0 END AS T_AL_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * F_CA_IM_QT),0) ELSE 0 END AS F_AL_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.QTR_END_DT, SUMM.PD_QT_ED_DT,(-1 * R_CA_IM_QT),0) ELSE 0 END AS R_AL_CA_IM_QT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * T_CA_IM_YT),0) ELSE 0 END AS T_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * F_CA_IM_YT),0) ELSE 0 END AS F_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * R_CA_IM_YT),0) ELSE 0 END AS R_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * T_CA_IM_YT),0) ELSE 0 END AS T_AL_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * F_CA_IM_YT),0) ELSE 0 END AS F_AL_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,(-1 * R_CA_IM_YT),0) ELSE 0 END AS R_AL_CA_IM_YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN (-1 * NVL(T_CA_IM_UT,0)) ELSE 0 END AS T_TL_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN (-1 * NVL(F_CA_IM_UT,0)) ELSE 0 END AS F_TL_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG IN ('DEF','EDEF') THEN (-1 * NVL(R_CA_IM_UT,0)) ELSE 0 END AS R_TL_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN  (-1 * NVL(T_CA_IM_UT,0)) ELSE 0 END AS T_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN  (-1 * NVL(F_CA_IM_UT,0)) ELSE 0 END AS F_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'DEF' THEN  (-1 * NVL(R_CA_IM_UT,0)) ELSE 0 END AS R_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN (-1 * NVL(T_CA_IM_UT,0)) ELSE 0 END AS T_AL_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN (-1 * NVL(F_CA_IM_UT,0)) ELSE 0 END AS F_AL_CA_IM_UT
,CASE WHEN ACG.DEF_REC_FLAG = 'EDEF' THEN (-1 * NVL(R_CA_IM_UT,0)) ELSE 0 END AS R_AL_CA_IM_UT
-- Retro QT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_RT_AR_QT,0) ELSE 0 END AS F_RT_QT  -- Contractual Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,F_RT_AR_QT,0) ELSE 0 END AS F_AR_RT_QT  -- Rev Adj Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_RT_AR_QT,0) ELSE 0 END AS T_RT_QT  -- Contractual Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,T_RT_AR_QT,0) ELSE 0 END AS T_AR_RT_QT  -- Rev Adj Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_RT_AR_QT,0) ELSE 0 END AS R_RT_QT  -- Contractual Retro Adj
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.QTR_END_DT,SUMM.PD_QT_ED_DT,R_RT_AR_QT,0) ELSE 0 END AS R_AR_RT_QT  -- Rev Adj Retro
--Retro YT
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_RT_AR_YT,0) ELSE 0 END AS F_RT_YT  -- Contractual Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,F_RT_AR_YT,0) ELSE 0 END AS F_AR_RT_YT  -- Rev Adj Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_RT_AR_YT,0) ELSE 0 END AS T_RT_YT  -- Contractual Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,T_RT_AR_YT,0) ELSE 0 END AS T_AR_RT_YT  -- Rev Adj Retro
,CASE WHEN ACG.DEF_REC_FLAG IN ('REC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_RT_AR_YT,0) ELSE 0 END AS R_RT_YT  -- Contractual Retro Adj
,CASE WHEN ACG.DEF_REC_FLAG IN ('EREC') THEN DECODE(CAL.YEAR_END_DT,SUMM.PD_YR_ED_DT,R_RT_AR_YT,0) ELSE 0 END AS R_AR_RT_YT  -- Rev Adj Retro
,DECODE (ACG.VC_FLAG, 'Y', summ.t_bb, 0) T_VC_BB
,DECODE (ACG.VC_FLAG, 'Y', summ.t_ad, 0) T_VC_AD
,DECODE (ACG.VC_FLAG, 'Y', summ.t_rl, 0) T_VC_RL
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',T_RL,0), 0) AS T_VC_CLM
,DECODE (ACG.VC_FLAG, 'Y', summ.t_eb, 0) T_VC_EB
,DECODE (ACG.VC_FLAG, 'Y', summ.f_bb, 0) F_VC_BB
,DECODE (ACG.VC_FLAG, 'Y', summ.f_ad, 0) F_VC_AD
,DECODE (ACG.VC_FLAG, 'Y', summ.f_rl, 0) F_VC_RL
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',F_RL,0), 0) AS F_VC_CLM
,DECODE (ACG.VC_FLAG, 'Y', summ.f_eb, 0) F_VC_EB
,DECODE (ACG.VC_FLAG, 'Y', summ.r_bb, 0) R_VC_BB
,DECODE (ACG.VC_FLAG, 'Y', summ.r_ad, 0) R_VC_AD
,DECODE (ACG.VC_FLAG, 'Y', summ.r_rl, 0) R_VC_RL
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',R_RL,0), 0) AS R_VC_CLM
,DECODE (ACG.VC_FLAG, 'Y', summ.r_eb, 0) R_VC_EB
,DECODE (ACG.VC_FLAG, 'Y', summ.t_bb_qt, 0) T_VC_BB_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.t_ad_qt, 0) T_VC_AD_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.t_rl_qt, 0) T_VC_RL_QT
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',T_RL_QT,0), 0) AS T_VC_CLM_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.f_bb_qt, 0) F_VC_BB_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.f_ad_qt, 0) F_VC_AD_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.f_rl_qt, 0) F_VC_RL_QT
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',F_RL_QT,0), 0) AS F_VC_CLM_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.r_bb_qt, 0) R_VC_BB_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.r_ad_qt, 0) R_VC_AD_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.r_rl_qt, 0) R_VC_RL_QT
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',R_RL_QT,0), 0) AS R_VC_CLM_QT
,DECODE (ACG.VC_FLAG, 'Y', summ.t_bb_yt, 0) T_VC_BB_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.t_ad_yt, 0) T_VC_AD_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.t_rl_yt, 0) T_VC_RL_YT
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',T_RL_YT,0), 0) AS T_VC_CLM_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.f_bb_yt, 0) F_VC_BB_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.f_ad_yt, 0) F_VC_AD_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.f_rl_yt, 0) F_VC_RL_YT
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',F_RL_YT,0), 0) F_VC_CLM_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.r_bb_yt, 0) R_VC_BB_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.r_ad_yt, 0) R_VC_AD_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.r_rl_yt, 0) R_VC_RL_YT
,DECODE (ACG.VC_FLAG, 'Y', DECODE(ACG.VC_CLR_FLAG,'Y',R_RL_YT,0), 0) AS R_VC_CLM_YT
,DECODE (ACG.VC_FLAG, 'Y', summ.T_UN, 0) AS T_VC_UN
,DECODE (ACG.VC_FLAG, 'Y', summ.F_UN, 0) AS F_VC_UN
,DECODE (ACG.VC_FLAG, 'Y', summ.R_UN, 0) AS R_VC_UN
,DECODE (ACG.VC_FLAG, 'Y', summ.T_PS, 0) AS T_VC_PS
,DECODE (ACG.VC_FLAG, 'Y', summ.F_PS, 0) AS F_VC_PS
,DECODE (ACG.VC_FLAG, 'Y', summ.R_PS, 0) AS R_VC_PS
,DECODE (ACG.VC_FLAG, 'Y', summ.T_AT_UT, 0) AS T_TL_VC_UT
,DECODE (ACG.VC_FLAG, 'Y', summ.F_AT_UT, 0) AS F_TL_VC_UT
,DECODE (ACG.VC_FLAG, 'Y', summ.R_AT_UT, 0) AS R_TL_VC_UT
,ACG.PAYABLES_ACCT_FLAG AS PAYABLES_ACCT_FLAG
,NVL(LTST.LT_T_BAL, 0) LT_T_BAL
,NVL(LTST.LT_F_BAL, 0) LT_F_BAL
,NVL(LTST.LT_R_BAL, 0) LT_R_BAL
,CASE WHEN ACG.ACCT_GROUP IN ('DREV', 'EDREV') THEN NVL(T_AD_UT,0) ELSE 0 END AS T_CUM_BILL_UTD
,CASE WHEN ACG.ACCT_GROUP IN ('DREV', 'EDREV') THEN NVL(F_AD_UT,0) ELSE 0 END AS F_CUM_BILL_UTD
FROM RPRO_RI_ACCT_SUMM_G SUMM
 INNER JOIN
     RPRO_CALENDAR_V CAL ON (CAL.END_DATE BETWEEN SUMM.VALID_FROM AND SUMM.VALID_UNTIL)
                        AND (CAL.client_id = SUMM.client_id)
 INNER JOIN
     RPRO_RI_ACCT_GRP_VM ACG ON (SUMM.ACCT_TYPE_ID = ACG.ID)
                            AND (SUMM.client_id = ACG.client_id)
 LEFT OUTER JOIN
     RPRO_LTST_SUMM_G LTST ON (SUMM.ROOT_LINE_ID = LTST.ROOT_LINE_ID)
                          AND (SUMM.ACCT_TYPE_ID = LTST.ACCT_TYPE_ID)
                          AND (SUMM.ACCTG_SEGS = LTST.ACCT_SEG)
                          AND (CAL.ID = LTST.PRD_ID)
                          AND (SUMM.CLIENT_ID = LTST.CLIENT_ID)
                          AND SUMM.SCHD_TYPE != 'D';
/