
  CREATE TABLE rpro_cust_wf_tbl 
   (	ID               NUMBER, 
	    rc_id            NUMBER, 
	    TYPE             VARCHAR2(20 ), 
	    rc_pob_id        NUMBER, 
	    ext_sll_prc      NUMBER, 
	    ext_fv_prc       NUMBER, 
	    def_amt          NUMBER, 
	    rec_amt          NUMBER, 
	    cv_amt           NUMBER, 
	    alctbl_xt_prc    NUMBER, 
	    alctd_xt_prc     NUMBER, 
	    bld_def_amt      NUMBER, 
	    bld_rec_amt      NUMBER, 
	    cstmr_nm         VARCHAR2(257 ), 
	    doc_num          VARCHAR2(257 ), 
	    doc_date         DATE, 
	    doc_line_num     VARCHAR2(257 ), 
	    doc_line_id      VARCHAR2(257 ), 
	    item_num         VARCHAR2(257 ), 
	    bndl_cnfg_id     NUMBER, 
	    ord_qty          NUMBER, 
	    inv_qty          NUMBER, 
	    ret_qty          NUMBER, 
	    start_date       DATE, 
	    end_date         DATE, 
	    duration         NUMBER, 
	    ext_lst_prc      NUMBER, 
	    indicators       VARCHAR2(80 ), 
	    batch_id         NUMBER, 
	    book_id          NUMBER, 
	    curr             VARCHAR2(10 ), 
	    f_cur            VARCHAR2(10 ), 
	    f_ex_rate        NUMBER, 
	    g_ex_rate        NUMBER, 
	    disc_amt         NUMBER, 
	    disc_pct         NUMBER, 
	    alctbl_fn_xt_prc NUMBER, 
	    ref_doc          VARCHAR2(500 ), 
	    ref_doc_line_id  VARCHAR2(257 ), 
	    lt_def_acnt      VARCHAR2(257 ), 
	    fv_grp_id        NUMBER, 
	    fv_pct           NUMBER, 
	    fv_prc           NUMBER, 
	    fv_type          VARCHAR2(20 ), 
	    err_msg          VARCHAR2(257), 
	    def_segments     VARCHAR2(260), 
	    rev_segments     VARCHAR2(260), 
	    atr1             VARCHAR2(257), 
	    atr2             VARCHAR2(257), 
	    atr3             VARCHAR2(257), 
	    atr4             VARCHAR2(257), 
	    atr5             VARCHAR2(257), 
	    atr6             VARCHAR2(257), 
	    atr7             VARCHAR2(257), 
	    atr8             VARCHAR2(257), 
	    atr9             VARCHAR2(257), 
	    atr10            VARCHAR2(257), 
	    atr11            VARCHAR2(257), 
	    atr12            VARCHAR2(257), 
	    atr13            VARCHAR2(257), 
	    atr14            VARCHAR2(257), 
	    atr15            VARCHAR2(257), 
	    atr16            VARCHAR2(257), 
	    atr17            VARCHAR2(257), 
	    atr18            VARCHAR2(257), 
	    atr19            VARCHAR2(257), 
	    atr20            VARCHAR2(257), 
	    atr21            VARCHAR2(257), 
	    atr22            VARCHAR2(257), 
	    atr23            VARCHAR2(257), 
	    atr24            VARCHAR2(257), 
	    atr25            VARCHAR2(257), 
	    atr26            VARCHAR2(257), 
	    atr27            VARCHAR2(257), 
	    atr28            VARCHAR2(257), 
	    atr29            VARCHAR2(257), 
	    atr30            VARCHAR2(257), 
	    atr31            VARCHAR2(257), 
	    atr32            VARCHAR2(257), 
	    atr33            VARCHAR2(257), 
	    atr34            VARCHAR2(257), 
	    atr35            VARCHAR2(257), 
	    atr36            VARCHAR2(257), 
	    atr37            VARCHAR2(257), 
	    atr38            VARCHAR2(257), 
	    atr39            VARCHAR2(257), 
	    atr40            VARCHAR2(257), 
	    atr41            VARCHAR2(257), 
	    atr42            VARCHAR2(257), 
	    atr43            VARCHAR2(257), 
	    atr44            VARCHAR2(257), 
	    atr45            VARCHAR2(257), 
	    atr46            VARCHAR2(257), 
	    atr47            VARCHAR2(257), 
	    atr48            VARCHAR2(257), 
	    atr49            VARCHAR2(257), 
	    atr50            VARCHAR2(257), 
	    atr51            VARCHAR2(257), 
	    atr52            VARCHAR2(257), 
	    atr53            VARCHAR2(257), 
	    atr54            VARCHAR2(257), 
	    atr55            VARCHAR2(257), 
	    atr56            VARCHAR2(257), 
	    atr57            VARCHAR2(257), 
	    atr58            VARCHAR2(257), 
	    atr59            VARCHAR2(257), 
	    atr60            VARCHAR2(257), 
	    num1             NUMBER, 
	    num2             NUMBER, 
	    num3             NUMBER, 
	    num4             NUMBER, 
	    num5             NUMBER, 
	    num6             NUMBER, 
	    num7             NUMBER, 
	    num8             NUMBER, 
	    num9             NUMBER, 
	    num10            NUMBER, 
	    num11            NUMBER, 
	    num12            NUMBER, 
	    num13            NUMBER, 
	    num14            NUMBER, 
	    num15            NUMBER, 
	    date1            DATE, 
	    date2            DATE, 
	    date3            DATE, 
	    date4            DATE, 
	    date5            DATE, 
	    client_id        NUMBER, 
	    crtd_prd_id      NUMBER, 
	    sec_atr_val      VARCHAR2(257 ), 
	    crtd_by          VARCHAR2(257 ), 
	    crtd_dt          DATE, 
	    updt_by          VARCHAR2(257 ), 
	    updt_dt          DATE, 
	    model_id         NUMBER, 
	    unschd_adj       NUMBER, 
	    posted_pct       NUMBER, 
	    rel_pct          NUMBER, 
	    term             NUMBER, 
	    vc_type_id       NUMBER, 
	    po_num           VARCHAR2(257 ), 
	    quote_num        VARCHAR2(257 ), 
	    schd_ship_dt     DATE, 
	    ship_dt          DATE, 
	    sales_rep_name   VARCHAR2(257 ), 
	    cust_num         VARCHAR2(257 ), 
	    prod_ctgry       VARCHAR2(257 ), 
	    prod_class       VARCHAR2(257 ), 
	    prod_fmly        VARCHAR2(257 ), 
	    prod_ln          VARCHAR2(257 ), 
	    business_unit    VARCHAR2(257 ), 
	    ct_mod_date      DATE, 
	    cum_cv_amt       NUMBER, 
	    cum_alctd_amt    NUMBER, 
	    comments         VARCHAR2(4000 ), 
	    prnt_ln_id       NUMBER, 
	    prnt_ref_ln_id   NUMBER, 
	    ct_date          DATE, 
	    ct_line_id       VARCHAR2(257 ), 
	    ct_line_num      VARCHAR2(257 ), 
	    ct_num           VARCHAR2(257 ), 
	    offset_segments  VARCHAR2(260 ), 
	    sob_id           NUMBER, 
	    fv_date          DATE, 
	    orig_fv_dt       DATE, 
	    vc_amt           NUMBER, 
	    lvl1_alctbl_xt_prc  NUMBER, 
	    lvl1_cv_amount      NUMBER, 
	    lvl1_alctd_xt_prc   NUMBER, 
	    lvl1_fv_prc         NUMBER, 
	    lvl1_fv_pct         NUMBER, 
	    lvl1_fv_grp_id      NUMBER, 
	    lvl2_alloc_pct      NUMBER, 
	    unit_sell_prc       NUMBER, 
	    unit_list_prc       NUMBER, 
	    impair_retrieve_amt NUMBER, 
	    bndl_prnt_id        VARCHAR2(257 ), 
	    company_code        VARCHAR2(257 ), 
	    cancel_flag         VARCHAR2(1 ), 
	    below_fv_prc        NUMBER, 
	    above_fv_prc        NUMBER, 
	    fv_tmpl_id          NUMBER, 
	    fv_expr             VARCHAR2(4000 ), 
	    below_mid_pct       NUMBER, 
	    above_mid_pct       NUMBER, 
	    ic_account          VARCHAR2(257 ), 
	    ca_account          VARCHAR2(257 ), 
	    ci_account          VARCHAR2(257 ), 
	    al_account          VARCHAR2(257 ), 
	    ar_account          VARCHAR2(257 ), 
	    contra_ar_acct      VARCHAR2(257 ), 
	    payables_acct       VARCHAR2(257 ), 
	    lt_def_adj_acct     VARCHAR2(257 ), 
	    ub_liab_acct        VARCHAR2(257 ), 
	    lt_def_cogs_acct    VARCHAR2(257 ), 
	    lt_ca_account       VARCHAR2(257 ), 
	    tot_bgd_hrs         NUMBER, 
	    tot_bgd_cst         NUMBER, 
	    fcst_date           DATE, 
	    link_identifier     VARCHAR2(257 ), 
	    prod_life_term      NUMBER, 
	    ramp_identifier     VARCHAR2(257 ), 
	    mr_line_id          NUMBER, 
	    price_point         VARCHAR2(257 ), 
	    tp_pct_ssp          NUMBER, 
	    orig_quantity       NUMBER, 
	    split_ref_doc_line_id VARCHAR2(257 ), 
	    overstated_amt NUMBER, 
	    ovst_lst_amt   NUMBER, 
	    ref_rc_id      NUMBER, 
	    mr_org_prc     NUMBER, 
	    action_type    VARCHAR2(257 ), 
	    pord_def_amt   NUMBER, 
	    pord_rec_amt   NUMBER, 
	    net_sll_prc    NUMBER, 
	    net_lst_prc    NUMBER, 
	    cv_amt_imprtmt NUMBER, 
	    subscrp_id     VARCHAR2(257 ), 
	    subscrp_name   VARCHAR2(257 ), 
	    subscrp_version    NUMBER, 
	    subscrp_start_date DATE, 
	    subscrp_end_date   DATE, 
	    subscrp_owner      VARCHAR2(257 ), 
	    invoice_owner      VARCHAR2(257 ), 
	    rp_id           VARCHAR2(257 ), 
	    rp_name         VARCHAR2(257 ), 
	    rpc_num         VARCHAR2(257 ), 
	    rpc_name        VARCHAR2(257 ), 
	    rpc_version     NUMBER, 
	    rpc_model       VARCHAR2(257 ), 
	    rpc_type        VARCHAR2(257 ), 
	    rpc_trigger_evt VARCHAR2(257 ), 
	    rpc_segment     VARCHAR2(257 ), 
	    rpc_id          VARCHAR2(257 ), 
	    orig_rpc_id     VARCHAR2(257 ), 
	    subscrp_type    VARCHAR2(257 ), 
	    charge_level    VARCHAR2(257 ), 
	    amendment_id    VARCHAR2(257 ), 
	    amendment_type  VARCHAR2(257 ), 
	    amendment_reason VARCHAR2(257 ), 
	    order_id         VARCHAR2(257 ), 
	    order_item_id    VARCHAR2(257 ), 
	    order_action_id  VARCHAR2(257 ), 
	    account_id       VARCHAR2(257 ), 
	    product_id       VARCHAR2(257 ), 
	    product_rp_id    VARCHAR2(257 ), 
	    product_rpc_id   VARCHAR2(257 ), 
	    charge_crtd_date      DATE, 
	    charge_last_updt_date DATE, 
	    bill_id               VARCHAR2(257 ), 
	    bill_item_id          VARCHAR2(257 ), 
	    zbill_batch_id        NUMBER, 
	    ramp_deal_ref         VARCHAR2(257 ), 
	    seq_num               VARCHAR2(257 ), 
	    avg_prcing_mthd       VARCHAR2(257 ), 
	    prc_frmt          VARCHAR2(257 ), 
	    prnt_chrg_segment VARCHAR2(257 ), 
	    prnt_chrg_num     VARCHAR2(257 ), 
	    entity_id         VARCHAR2(257 ), 
	    ssp_sll_prc       NUMBER, 
	    ssp_lst_prc       NUMBER, 
	    subscrp_trm_st_dt DATE, 
	    subscrp_trm_end_dt DATE, 
	    prd_id NUMBER, 
	    amount NUMBER
   );